name: TIC code tests

on:
  push:
    branches: [ "main", "ghci" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pushd transparency-in-coverage/python/mrfutils
        pip install -r requirements.txt
        popd
    - name: Run unit tests
      run: |
        pushd transparency-in-coverage/python/mrfutils/tests
        python tests.py
        popd
